// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const REMOTE_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const USE_SUPABASE_DEV_PROXY = import.meta.env.DEV && import.meta.env.VITE_USE_SUPABASE_DEV_PROXY === "true";
const SUPABASE_URL = USE_SUPABASE_DEV_PROXY
  ? `${window.location.origin}/supabase`
  : REMOTE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const SUPABASE_PROJECT_REF = REMOTE_SUPABASE_URL
  ? new URL(REMOTE_SUPABASE_URL).hostname.split(".")[0]
  : "supabase";
const SUPABASE_STORAGE_KEY = `sb-${SUPABASE_PROJECT_REF}-auth-token`;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    storageKey: SUPABASE_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
  }
});
